{{- if and .Values.metrics.service.enabled .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gwb-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gwb-operator.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "gwb-operator.selectorLabels" . | nindent 6 }}
      control-plane: controller-manager
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: https
      path: /metrics
      scheme: {{ .Values.metrics.serviceMonitor.scheme }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: {{ .Values.metrics.serviceMonitor.insecureSkipVerify }}
{{- end }}
