//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Enforcement) DeepCopyInto(out *Enforcement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Enforcement.
func (in *Enforcement) DeepCopy() *Enforcement {
	if in == nil {
		return nil
	}
	out := new(Enforcement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUWorkloadBudget) DeepCopyInto(out *GPUWorkloadBudget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUWorkloadBudget.
func (in *GPUWorkloadBudget) DeepCopy() *GPUWorkloadBudget {
	if in == nil {
		return nil
	}
	out := new(GPUWorkloadBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUWorkloadBudget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUWorkloadBudgetList) DeepCopyInto(out *GPUWorkloadBudgetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUWorkloadBudget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUWorkloadBudgetList.
func (in *GPUWorkloadBudgetList) DeepCopy() *GPUWorkloadBudgetList {
	if in == nil {
		return nil
	}
	out := new(GPUWorkloadBudgetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUWorkloadBudgetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUWorkloadBudgetSpec) DeepCopyInto(out *GPUWorkloadBudgetSpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	in.Quota.DeepCopyInto(&out.Quota)
	out.Enforcement = in.Enforcement
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUWorkloadBudgetSpec.
func (in *GPUWorkloadBudgetSpec) DeepCopy() *GPUWorkloadBudgetSpec {
	if in == nil {
		return nil
	}
	out := new(GPUWorkloadBudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUWorkloadBudgetStatus) DeepCopyInto(out *GPUWorkloadBudgetStatus) {
	*out = *in
	out.ConsumedGPUHours = in.ConsumedGPUHours.DeepCopy()
	out.RemainingGPUHours = in.RemainingGPUHours.DeepCopy()
	if in.LastEnforcementAt != nil {
		in, out := &in.LastEnforcementAt, &out.LastEnforcementAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUWorkloadBudgetStatus.
func (in *GPUWorkloadBudgetStatus) DeepCopy() *GPUWorkloadBudgetStatus {
	if in == nil {
		return nil
	}
	out := new(GPUWorkloadBudgetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Quota) DeepCopyInto(out *Quota) {
	*out = *in
	out.GPUHours = in.GPUHours.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Quota.
func (in *Quota) DeepCopy() *Quota {
	if in == nil {
		return nil
	}
	out := new(Quota)
	in.DeepCopyInto(out)
	return out
}
